services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "3000:3000"

  app:
    build: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PYTHONPATH=${PYTHONPATH}
    command:
      - uvicorn main:app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pg-data: