services:
  db:
    image: postgres:17
    command: -p 6000
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "6000:6000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB:-training_db}

  redis:
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.3.1-amd64
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kafka:
    image: apache/kafka:4.3.0
    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
      - kf_data:/usr/share/apache_kafka/data
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT #TODO move kafka-specific vars to .kafka.env
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

  app:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - elastic

volumes:
  es_data:
    driver: local
  pg_data:
    driver: local
  kf_data:
    driver: local