[project]
name = "training-app"
version = "0.0.1"
dependencies = [
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "asyncpg",
    "python-dotenv",
    "alembic",
    "pydantic[email]",
    "pydantic-settings",
    "pyjwt",
    "psycopg2-binary",
    "cryptography",
    "python-jose",
    "redis",
    "elasticsearch",
    "elasticsearch_dsl",
    "aiohttp>=3.13.3",
    "faker",
    "jinja2",
    "confluent_kafka"
]
[project.optional-dependencies]
test = [
    "pytest>=8.0",
    "pytest-asyncio>=0.24",
    "httpx>=0.27",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
pythonpath = ["."]

[tool.uv]
native-tls = true
