"""renamed status to access_level

Revision ID: 3e4beb0721bc
Revises: aaabecb8f18e
Create Date: 2026-03-06 13:27:00.367087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e4beb0721bc'
down_revision: Union[str, Sequence[str], None] = 'aaabecb8f18e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_level', sa.Enum('ORDINARY', 'MODERATOR', name='usertype'), nullable=True))
    op.drop_column('users', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', postgresql.ENUM('ORDINARY', 'MODERATOR', name='usertype'), autoincrement=False, nullable=True))
    op.drop_column('users', 'access_level')
    # ### end Alembic commands ###
