"""add rejected_forms table

Revision ID: 0acd6c73f3dd
Revises: 3e4beb0721bc
Create Date: 2026-04-10 15:37:11.007008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0acd6c73f3dd'
down_revision: Union[str, Sequence[str], None] = '3e4beb0721bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rejected_forms',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rejected_form_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['rejected_form_id'], ['form.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'rejected_form_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rejected_forms')
    # ### end Alembic commands ###
