"""added status field to user table

Revision ID: aaabecb8f18e
Revises: 5426465d51a2
Create Date: 2026-03-05 21:07:13.357526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaabecb8f18e'
down_revision: Union[str, Sequence[str], None] = '5426465d51a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    status_type = sa.Enum('ORDINARY', 'MODERATOR', name='usertype')
    status_type.create(op.get_bind())

    op.add_column('users', sa.Column('status', sa.Enum('ORDINARY', 'MODERATOR', name='usertype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')

    sa.Enum(name='usertype').create(op.get_bind())
    # ### end Alembic commands ###
